services:
  attacker:
    build: ./attacker
    container_name: attacker_node
    networks:
      external_net:
        ipv4_address: 10.0.0.10

  victim1:
    build: ./victim1
    container_name: victim_1
    networks:
      external_net:
        ipv4_address: 10.0.0.20
      internal_net:
        ipv4_address: 192.168.10.20

  victim2:
    build: ./victim2
    container_name: victim_2
    networks:
      internal_net:
        ipv4_address: 192.168.10.30
        
  final_victim:
    build: ./final_victim
    container_name: final_victim
    networks:
      internal_net:
        ipv4_address: 192.168.10.40

  ids:
    image: jasonish/suricata:latest
    container_name: ids_node
    network_mode: "service:victim1" 
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    command: -i eth0 -i eth1
    volumes:
      - ./ids/logs:/var/log/suricata
      - ./ids/local.rules:/etc/suricata/local.rules

networks:
  external_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
